# 2D Numpy in Python

Estimated time needed: **20** minutes

## Objectives

After completing this lab you will be able to:

* Operate comfortably with `numpy`
* Perform complex operations with `numpy`

## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="create">Create a 2D Numpy Array</a></li>
        <li><a href="access">Accessing different elements of a Numpy Array</a></li>
        <li><a href="op">Basic Operations</a></li>
    </ul>
  
</div>

---

## Creating 2D Numpy Arrays

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

Consider the list, which contains 3 nested lists, each of equal size, below. We can cast the list to a NumPy array (every element of the same type).

In [2]:
## Create list
list_num = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(list_num)
## Convert list to NumPy array
N = np.array(list_num)
print(N)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]


We can use the attribute `ndim` to obtain the number of axes or dimensions, referred to as the rank. 

In [3]:
## Show number of array dimensions
print(N.ndim)

2


Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.


In [4]:
## Show the shape of the array
print(N.shape)

(3, 3)


The total number of elements in the array is given by the attribute `size`.

In [5]:
## Show the number of elements in array
print(N.size)

9


## Accessing Different Elements of Numpy Array

We can use square brackets to access the different elements of the array. The correspondence between the square brackets and the list and the rectangular representation for a 3x3 array is shown below.

`N: [[N[0, 0], N[0, 1], N[0, 2]], [N[1, 0], N[1, 1], N[1, 2]], [N[2, 0], N[2, 1], N[2, 2]]]`

$$
\begin{bmatrix}
N[0, 0] & N[0, 1] & N[0, 2] \\
N[1, 0] & N[1, 1] & N[1, 2] \\
N[2, 0] & N[2, 1] & N[2, 2] \\
\end{bmatrix}
$$

We can access the 2nd-row, 3rd column as shown in the following figure.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">

We simply use the square brackets and the indices corresponding to the element to access it.

In [6]:
## Access the element at the 2nd row and 3rd column
N[1, 2]

23

We can also use the following notation to obtain the element.

In [7]:
## Access the element at the 2nd row and 3rd column
N[1][2]

23

Consider the element shown in the following figure.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400">


In [9]:
## Access the element at the 1st row and 1st column
N[0][0]

11

We can also slice NumPy arrays. Consider the following figure. We would like to obtain the 1st 2 columns in the 1st row.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">


In [10]:
## Access the elements in the 1st columns (indices 0 and 1) of the 1st row (index 0)
N[0][0:2]

array([11, 12])

Similarly, we can obtain the 1st 2 rows of the 3rd column as follows.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="550"><br />


In [11]:
## Access the elements in the 3rd column (index 2) of the 1st 2 rows (indices 0 and 1)
N[0:2, 2]

array([13, 23])

## Basic Operations

We can also add arrays. The process is identical to matrix addition.

**Matrix Addition**

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">

In [14]:
## Create NumPy arrays X and Y
X = np.array([[1, 0], [0, 1]]) 
print(X)
Y = np.array([[2, 1], [1, 2]]) 
print(Y)

[[1 0]
 [0 1]]
[[2 1]
 [1 2]]


We can add the NumPy arrays as follows.

In [16]:
## Add NumPy arrays
Z = X + Y
print(Z)

[[3 1]
 [1 3]]


Multiplying a NumPy array by a scalar is identical to multiplying a matrix by a scalar. If we multiply the matrix `Y` by the scalar 2, we simply multiply every element in the matrix by 2. See below.

$$
\begin{equation*}
Y 
= 
\begin{bmatrix}
2 & 1 \\
1 & 2 \\
\end{bmatrix}
\end{equation*}
$$

<!-- Matrix equation on one line -->

$$
\begin{equation*}
2Y
=
\begin{bmatrix}
2\times2 & 1\times2 \\
1\times2 & 2\times2 \\
\end{bmatrix}
=
\begin{bmatrix}
4 & 2 \\
2 & 4 \\
\end{bmatrix}
\end{equation*}
$$

<!-- Matrix equation on multiple lines -->

$$
\eqalign{
2Y
&= \begin{bmatrix}
2\times2 & 1\times2 \\
1\times2 & 2\times2 \\
\end{bmatrix} \\
&= \begin{bmatrix}
4 & 2 \\
2 & 4 \\
\end{bmatrix} \\
}
$$

We can perform the same operation in numpy as follows 


In [ ]:
## Create NumPy array Y
Y = np.array([[2, 1], [1, 2]]) 
Y
# Multiply Y with 2
Z = 2 * Y
Z

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">


We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:


In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

In [ ]:
# Multiply X with Y

Z = X * Y
Z

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:


First, we define matrix <code>A</code> and <code>B</code>:


In [ ]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

In [ ]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

We use the numpy function <code>dot</code> to multiply the arrays together.


In [ ]:
# Calculate the dot product

Z = np.dot(A,B)
Z

In [ ]:
# Calculate the sine of Z

np.sin(Z)

We use the numpy attribute <code>T</code> to calculate the transposed matrix


In [ ]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

In [ ]:
# Get the transposed of C

C.T

---

## Exercises

### 2D Numpy Array

Consider the following list <code>a</code>, convert it to Numpy Array. 


In [ ]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<details><summary>Click here for the solution</summary>

```python
A = np.array(a)
A
```

</details>


Calculate the numpy array size.


In [ ]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A.size
```

</details>


Access the element on the first row and first and second columns.


In [ ]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A[0][0:2]
```

</details>


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [ ]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

<details><summary>Click here for the solution</summary>

```python
X = np.dot(A,B)
X
```

</details>


---

Author(s):

- [Joseph Santarcangelo](https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01)

Other Contributor(s):

- [Mavis Zhou](www.linkedin.com/in/jiahui-mavis-zhou-a4537814a)