# 2D Numpy in Python

Estimated time needed: **20** minutes

## Objectives

After completing this lab you will be able to:

* Operate comfortably with `numpy`
* Perform complex operations with `numpy`

## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="create">Create a 2D Numpy Array</a></li>
        <li><a href="access">Accessing different elements of a Numpy Array</a></li>
        <li><a href="op">Basic Operations</a></li>
    </ul>
  
</div>

---

## Creating 2D Numpy Arrays

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

Consider the list, which contains 3 nested lists, each of equal size, below. We can cast the list to a NumPy array (every element of the same type).

In [2]:
## Create list
list_int = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(list_int)
## Convert list to NumPy array
arr_int = np.array(list_int)
print(arr_int)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]


We can use the attribute `ndim` to obtain the number of axes or dimensions, referred to as the rank. 

In [3]:
## Show number of array dimensions
print(arr_int.ndim)

2

Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.


In [5]:
## Show the shape of the array
print(arr_int.shape)

(3, 3)


The total number of elements in the array is given by the attribute `size`.

In [6]:
## Show the number of elements in array
print(arr_int.size)

9


## Accessing Different Elements of Numpy Array

We can use square brackets to access the different elements of the array. The correspondence between the square brackets and the list and the rectangular representation for a 3x3 array is shown below.

`A: [[A[0, 0], A[0, 1], A[0, 2]], [A[1, 0], A[1, 1], A[1, 2]], [A[2, 0], A[2, 1], A[2, 2]]]`

$$
\begin{bmatrix}
A[0, 0] & A[0, 1] & A[0, 2] \\
A[1, 0] & A[1, 1] & A[1, 2] \\
A[2, 0] & A[2, 1] & A[2, 2]
\end{bmatrix}
$$

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">

We can access the 2nd-row, 3rd column as shown in the following figure.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


 We simply use the square brackets and the indices corresponding to the element we would like:


In [ ]:
# Access the element on the second row and third column

A[1, 2]

 We can also use the following notation to obtain the elements: 


In [ ]:
# Access the element on the second row and third column

A[1][2]

 Consider the elements shown in the following figure 


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400">


We can access the element as follows: 


In [ ]:
# Access the element on the first row and first column

A[0][0]

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">


 This can be done with the following syntax: 


In [ ]:
# Access the element on the first row and first and second columns

A[0][0:2]

Similarly, we can obtain the first two rows of the 3rd column as follows:


In [ ]:
# Access the element on the first and second rows and third column

A[0:2, 2]

Corresponding to the following figure: 


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="550"><br />


## Basic Operations

We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">


The numpy array is given by <code>X</code> and <code>Y</code>


In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

 We can add the numpy arrays as follows.


In [ ]:
# Add X and Y

Z = X + Y
Z

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">


We can perform the same operation in numpy as follows 


In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

In [ ]:
# Multiply Y with 2

Z = 2 * Y
Z

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">


We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:


In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

In [ ]:
# Multiply X with Y

Z = X * Y
Z

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:


First, we define matrix <code>A</code> and <code>B</code>:


In [ ]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

In [ ]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

We use the numpy function <code>dot</code> to multiply the arrays together.


In [ ]:
# Calculate the dot product

Z = np.dot(A,B)
Z

In [ ]:
# Calculate the sine of Z

np.sin(Z)

We use the numpy attribute <code>T</code> to calculate the transposed matrix


In [ ]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

In [ ]:
# Get the transposed of C

C.T

---

## Exercises

### 2D Numpy Array

Consider the following list <code>a</code>, convert it to Numpy Array. 


In [ ]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<details><summary>Click here for the solution</summary>

```python
A = np.array(a)
A
```

</details>


Calculate the numpy array size.


In [ ]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A.size
```

</details>


Access the element on the first row and first and second columns.


In [ ]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A[0][0:2]
```

</details>


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [ ]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

<details><summary>Click here for the solution</summary>

```python
X = np.dot(A,B)
X
```

</details>


---

Author(s):

- [Joseph Santarcangelo](https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01)

Other Contributor(s):

- [Mavis Zhou](www.linkedin.com/in/jiahui-mavis-zhou-a4537814a)