## Exercises

In [1]:
import numpy as np

### Numpy 2D Arrays Basics

We will use the NumPy array `A` for the following questions.

In [2]:
A = np.array([[11, 12], [21, 22], [31, 32]])

In [3]:
print(A)

[[11 12]
 [21 22]
 [31 32]]


1. Find the type of the array.

<details><summary>Click here for the solution</summary>

```python
type(A)
```
</details>

2. Find the shape of the array.

<details><summary>Click here for the solution</summary>

```python
A.shape
```

</details>

3. Find the type of data in the array.

<details><summary>Click here for the solution</summary>

```python
A.dtype
```

</details>

4. Find the second row of the array.

<details><summary>Click here for the solution</summary>

```python
A[1]
```

</details>

### Two Types of Multiplication

We will use the following arrays for the next questions.

In [4]:
A = np.array([[11, 12], [21, 22]])
B = np.array([[1, 0], [0, 1]])

In [5]:
print(A)
print(B)

[[11 12]
 [21 22]]
[[1 0]
 [0 1]]


1. Multiply array `A` and `B`.

<details><summary>Click here for the solution</summary>

```python
C = A * B
C
```

</details>

2. Perform matrix multiplication on array `A` and `B` (order not matter in this case).

<details><summary>Click here for the solution</summary>

```python
Z = np.dot(A,B)
Z
```

</details>